apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.1651        # applies to all detected tags
    max_hamming: 0
    publish_tf: true

    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
    detector:
      threads: 1 # number of threads
      decimate: 2.0 # decimate resolution for quad detection
      blur: 0.0 # sigma of Gaussian blur for quad detection
      refine: True # snap to strong gradients
      sharpening: 0.25 # sharpening of decoded images
      debug: False # write additional debugging images to current working directory
